SELECT DISTINCT v FROM foo2;

SELECT DISTINCT * FROM foo2;

SELECT DISTINCT a, b FROM foo3;

SELECT b FROM foo3;
SELECT DISTINCT b FROM foo3;

SELECT DISTINCT e FROM foo4;    -- 数据含有 NULL 的情况，结果中 NULL 也会当做一类
