SELECT * FROM foo2 WHERE id > 4 AND k > 4 AND k < 10;
SELECT * FROM foo2 WHERE id > 4 AND k < 4 ORDER BY v DESC;
SELECT * FROM foo2 WHERE id > 4 AND k < 4 ORDER BY v DESC;
SELECT * FROM foo2 WHERE id > 7 OR k < 4 AND v > 1;
SELECT * FROM foo2 WHERE (id > 7 OR k < 4) AND v > 1;

SELECT * FROM foo3 WHERE c > 1;
SELECT * FROM foo3 WHERE id = 1;
SELECT * FROM foo3 WHERE id <> 1;
SELECT * FROM foo3 WHERE id < 3;
SELECT * FROM foo3 WHERE id <= 3;
-- SELECT * FROM foo3 WHERE id !< 3;
SELECT * FROM foo3 WHERE id >= 2;
SELECT * FROM foo3 WHERE id > 2;
-- SELECT * FROM foo3 WHERE id !> 2;

SELECT * FROM foo3 WHERE id BETWEEN 2 AND 3;
SELECT * FROM foo3 WHERE id >= 2 AND id <= 3;

SELECT * FROM foo3 WHERE a is NULL;
SELECT * FROM foo3 WHERE a is NOT NULL;

SELECT * FROM foo4 WHERE e is NULL;
SELECT * FROM foo4 WHERE e is NOT NULL;
SELECT * FROM foo4 WHERE e < 100;
SELECT * FROM foo4 WHERE e != 100;

SELECT * FROM foo4 WHERE id IN (1, 2);
SELECT * FROM foo4 WHERE id IN (1);
-- SELECT * FROM foo4 WHERE id IN (1,);
SELECT * FROM foo4 WHERE id = 1 OR id = 2;

SELECT * FROM foo4 WHERE NOT e is NULL;
SELECT * FROM foo4 WHERE NOT id IN (1, 2);
SELECT * FROM foo4 WHERE NOT e < 30;
SELECT * FROM foo4 WHERE NOT e = 33;
SELECT * FROM foo4 WHERE NOT e != 33;
