SELECT COUNT(*) FROM foo4;
SELECT COUNT(id) FROM foo4;
SELECT COUNT(e) FROM foo4;
SELECT COUNT(0) FROM foo4;
SELECT COUNT(1) FROM foo4;
SELECT COUNT(2) FROM foo4;
SELECT COUNT(3) FROM foo4;
SELECT 0 FROM foo4;
SELECT 1 FROM foo4;


SELECT COUNT(DISTINCT e) FROM foo4;     -- 不计算 NULL
SELECT COUNT(DISTINCT b) FROM foo3;     -- 只计算不一样的数量
SELECT COUNT(b) FROM foo3;
